'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Your Company Name")>  _
    Public Property CompanyName() As String
        Get
            Return CType(Me("CompanyName"),String)
        End Get
        Set
            Me("CompanyName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Predefined Application Name")>  _
    Public Property ApplicationName() As String
        Get
            Return CType(Me("ApplicationName"),String)
        End Get
        Set
            Me("ApplicationName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Your Greetings Message")>  _
    Public Property GreetingsMessage() As String
        Get
            Return CType(Me("GreetingsMessage"),String)
        End Get
        Set
            Me("GreetingsMessage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ClientID() As String
        Get
            Return CType(Me("ClientID"),String)
        End Get
        Set
            Me("ClientID") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property HardwareID() As String
        Get
            Return CType(Me("HardwareID"),String)
        End Get
        Set
            Me("HardwareID") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property SerialNumber() As String
        Get
            Return CType(Me("SerialNumber"),String)
        End Get
        Set
            Me("SerialNumber") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("203.99.123.17")>  _
    Public Property DbIpAddress() As String
        Get
            Return CType(Me("DbIpAddress"),String)
        End Get
        Set
            Me("DbIpAddress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
    Public Property DbUsername() As String
        Get
            Return CType(Me("DbUsername"),String)
        End Get
        Set
            Me("DbUsername") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("P4tr4k0m*")>  _
    Public Property DbPassword() As String
        Get
            Return CType(Me("DbPassword"),String)
        End Get
        Set
            Me("DbPassword") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("patrakom_erp")>  _
    Public Property DbName() As String
        Get
            Return CType(Me("DbName"),String)
        End Get
        Set
            Me("DbName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("erp_employee_fingerprint")>  _
    Public Property FingerprintTable() As String
        Get
            Return CType(Me("FingerprintTable"),String)
        End Get
        Set
            Me("FingerprintTable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("erp_employee_attendances_logs")>  _
    Public Property AttendanceTable() As String
        Get
            Return CType(Me("AttendanceTable"),String)
        End Get
        Set
            Me("AttendanceTable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DeviceSerial() As String
        Get
            Return CType(Me("DeviceSerial"),String)
        End Get
        Set
            Me("DeviceSerial") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property VerificationCode() As String
        Get
            Return CType(Me("VerificationCode"),String)
        End Get
        Set
            Me("VerificationCode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ActivationCode() As String
        Get
            Return CType(Me("ActivationCode"),String)
        End Get
        Set
            Me("ActivationCode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property BackgroundImage() As String
        Get
            Return CType(Me("BackgroundImage"),String)
        End Get
        Set
            Me("BackgroundImage") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
    Public Property ButtonColor1() As Global.System.Drawing.Color
        Get
            Return CType(Me("ButtonColor1"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ButtonColor1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("64, 0, 0")>  _
    Public Property ButtonColor2() As Global.System.Drawing.Color
        Get
            Return CType(Me("ButtonColor2"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ButtonColor2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Vertical")>  _
    Public Property ButtonGradientMode() As String
        Get
            Return CType(Me("ButtonGradientMode"),String)
        End Get
        Set
            Me("ButtonGradientMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ApplicationLogo() As String
        Get
            Return CType(Me("ApplicationLogo"),String)
        End Get
        Set
            Me("ApplicationLogo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
    Public Property ApplicationLogoColor1() As Global.System.Drawing.Color
        Get
            Return CType(Me("ApplicationLogoColor1"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ApplicationLogoColor1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
    Public Property ApplicationLogoColor2() As Global.System.Drawing.Color
        Get
            Return CType(Me("ApplicationLogoColor2"),Global.System.Drawing.Color)
        End Get
        Set
            Me("ApplicationLogoColor2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Vertical")>  _
    Public Property ApplicationLogoGradientMode() As String
        Get
            Return CType(Me("ApplicationLogoGradientMode"),String)
        End Get
        Set
            Me("ApplicationLogoGradientMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("192, 0, 0")>  _
    Public Property HeaderColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("HeaderColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("HeaderColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Tahoma, 8.25pt, style=Bold")>  _
    Public Property FontFace() As Global.System.Drawing.Font
        Get
            Return CType(Me("FontFace"),Global.System.Drawing.Font)
        End Get
        Set
            Me("FontFace") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
    Public Property FontColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("FontColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("FontColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Tahoma, 14.25pt")>  _
    Public Property FontFaceProgress() As Global.System.Drawing.Font
        Get
            Return CType(Me("FontFaceProgress"),Global.System.Drawing.Font)
        End Get
        Set
            Me("FontFaceProgress") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
    Public Property FontFaceProgressColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("FontFaceProgressColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("FontFaceProgressColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("P4tr4k0m")>  _
    Public Property SecureKey() As String
        Get
            Return CType(Me("SecureKey"),String)
        End Get
        Set
            Me("SecureKey") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("erp_employee")>  _
    Public Property EmployeeTable() As String
        Get
            Return CType(Me("EmployeeTable"),String)
        End Get
        Set
            Me("EmployeeTable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("erp_employee_shifts")>  _
    Public Property ShiftTable() As String
        Get
            Return CType(Me("ShiftTable"),String)
        End Get
        Set
            Me("ShiftTable") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property WebcamDriverIndex() As Integer
        Get
            Return CType(Me("WebcamDriverIndex"),Integer)
        End Get
        Set
            Me("WebcamDriverIndex") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property WebcamDriverName() As String
        Get
            Return CType(Me("WebcamDriverName"),String)
        End Get
        Set
            Me("WebcamDriverName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property BackgroundImageSlideShowFolder() As String
        Get
            Return CType(Me("BackgroundImageSlideShowFolder"),String)
        End Get
        Set
            Me("BackgroundImageSlideShowFolder") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property BackgroundImageType() As Integer
        Get
            Return CType(Me("BackgroundImageType"),Integer)
        End Get
        Set
            Me("BackgroundImageType") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
    Public Property BackgroundImageSlideShowDuration() As Integer
        Get
            Return CType(Me("BackgroundImageSlideShowDuration"),Integer)
        End Get
        Set
            Me("BackgroundImageSlideShowDuration") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Stretch")>  _
    Public Property BackgroundMode() As String
        Get
            Return CType(Me("BackgroundMode"),String)
        End Get
        Set
            Me("BackgroundMode") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Patrakom.Settings
            Get
                Return Global.Patrakom.Settings.Default
            End Get
        End Property
    End Module
End Namespace
